# Generated by Django 3.1 on 2020-08-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('classof', models.CharField(max_length=50)),
                ('average', models.CharField(max_length=50)),
            ],
        ),
    ]
